#!/bin/bash

echo -e "AutoRiceVoidDesktopLinux\n<>  <>  <>\n<>  <>  <>\n<>  <>  <>"

# Update system
sudo xbps-install -Syu

# Install packages I like
sudo xbps-install -Sy alsa-utils base-devel base-system curl dmenu dunst emacs fd feh firefox font-awesome font-inconsolata-otf fzf giflib-devel git github-cli grub htop imlib2-devel jq lf libXft-devel libXinerama-devel libexif-devel libinput-gestures mpv neofetch neovim picom ripgrep scrot sxhkd tty-clock ueberzug vim wget wifish xbanish xdg-utils xdotool xorg xsel youtube-dl zathura zathura-pdf-poppler zsh

# Copy config/* to $HOME/.config/
mkdir -p $HOME/.config/
cp -r ./config/* $HOME/.config/
sudo mv $HOME/.config/zsh/.zshrc /root/
sudo ln -s $HOME/.config/zsh/aliases /root/.aliases
mkdir -p /root/.config/
sudo ln -s $HOME/.config/nvim/ /root/.config/nvim

# Sending files to specific locations
mkdir -p    $HOME/files/ \
            $HOME/files/pictures/ \
            $HOME/files/pictures/screenshots/ \
            $HOME/files/downloads/ \
            $HOME/files/backups/ \
            $HOME/files/github/ \
            $HOME/files/writing
cp -r ./backgrounds/ $HOME/files/pictures/

# Sending .otherfiles to specific locations
sudo cp $HOME/.config/.otherfiles/sudoers /etc/sudoers
# Send Sweet-cursors theme to defaults icons folder
sudo cp -r $HOME/.config/.otherfiles/Sweet-cursors /usr/share/icons/

# Symbolic link xinitrc
ln -sf $HOME/.config/X11/xinitrc $HOME/.xinitrc

# Symbolic link the zshrc file
ln -sf $HOME/.config/zsh/zshrc $HOME/.zshrc
sudo chsh -s /bin/zsh

# Install YTFZF
git clone https://github.com/pystardust/ytfzf.git
cd ytfzf
chmod +x ytfzf
sudo cp ytfzf /usr/local/bin/
cd ..
rm -rf ytfzf

# Recompile everything in suckelessutils/
bash $HOME/.config/sucklessutils/addons_dwm/full_make

echo -e "<>  <>  <>\n<>  <>  <>\n<>  <>  <>\nHope all went well!"
