#!/bin/bash

echo -e "AutoRiceVoidDesktopLinux\n<>  <>  <>\n<>  <>  <>\n<>  <>  <>"

# Fail proofing
sudo xbps-install -Syu xbps

# Update system
sudo xbps-install -Syu

# Install packages I like # NOT UPDATED
sudo xbps-install -Sy ImageMagick VeraCrypt acpi alsa-utils android-file-transfer-linux base-devel base-system cargo curl dmenu dunst fd feh ffmpeg figlet figlet-fonts firefox font-awesome font-inconsolata-otf freeimage fzf giflib-devel gimp git github-cli go gpick grub-x86_64-efi highlight htop i3lock-color imlib2-devel jq keepassxc krita libXft-devel libXinerama-devel libexif-devel libinput-gestures lua mpc mpd mpv ncmpcpp neofetch neovim nmap nodejs openjdk picom python3-pip qalculate ranger rsClock rust screenkey scrot sxhkd syncthing tectonic transmission tty-clock ueberzug vim wget xautolock xbanish xdg-utils xdotool xorg xsel youtube-dl zathura zathura-pdf-poppler zenity zip zsh

# Copy config/* to $HOME/.config/
mkdir -p $HOME/.config/
cp -r ./config/* $HOME/.config/

# Creating Dirs and moving backgrounds
mkdir -p    $HOME/files/ \
            $HOME/files/pictures/ \
            $HOME/files/pictures/screenshots/ \
            $HOME/files/downloads/ \
            $HOME/files/backups/ \
            $HOME/files/github/ \
            $HOME/files/music/ \
            $HOME/files/videos/ \
            $HOME/files/writing/
cp -r ./backgrounds/ $HOME/files/pictures/

# QEMU config
#sudo usermod -aG kvm <username>
#sudo modprobe kvm-intel

# Sending .otherfiles to specific locations
sudo cp ./config/.otherfiles/sudoers /etc/sudoers
# Send Sweet-cursors theme to defaults icons folder
sudo cp -r ./config/.otherfiles/Sweet-cursors /usr/share/icons/

# Symbolic link xinitrc
ln -sf $HOME/.config/X11/xinitrc $HOME/.xinitrc

# Symbolic link the zshrc file
ln -sf $HOME/.config/zsh/zshrc $HOME/.zshrc
chsh -s /bin/zsh
# Root stuff
sudo mv $HOME/.config/zsh/.zshrc /root/
sudo ln -s $HOME/.config/zsh/aliases /root/.aliases
sudo mkdir -p /root/.config/
sudo ln -s $HOME/.config/nvim/ /root/.config/
sudo chsh -s /bin/zsh

# Install YTFZF
curl -sL "https://raw.githubusercontent.com/pystardust/ytfzf/master/ytfzf" | sudo tee /usr/local/bin/ytfzf >/dev/null && sudo chmod 755 /usr/local/bin/ytfzf

# Install yt-dlp
sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /bin/youtube-dl && sudo chmod a+rx /bin/youtube-dl

# Recompile everything in suckelessutils/
bash $HOME/.config/sucklessutils/addons_dwm/full_make

echo -e "\nRun `\$ chsh -s /bin/zsh` if shell hasnt been changed for current user, do the same for root.\n"
echo -e "Fix ScreenTearing on X11\n"
echo -e "<>  <>  <>\n<>  <>  <>\n<>  <>  <>\nHope all went well!"
