#!/bin/bash

set -e 

DpreCONF=$(bash dwmcfg dmenucolor)

# Dont forget the slash at the end
menuLIST=( "tmenu" "bmenu" "smenu" "pmenu" )

menuSEL=$(echo -e "${menuLIST[0]}\n${menuLIST[1]}\n${menuLIST[2]}\n${menuLIST[3]}" | $DpreCONF -l 5)
bash $menuSEL
