#!/bin/bash

extension=$(echo $1 | sed -r 's/.*\.//g')
binary="bin_$(echo $1 | sed -r 's/\..*$//g')"

case $extension in
    "cpp")
        figlet -f shadow C + +
        g++ -o $binary $1
        ./$binary;;
    "rs")
        figlet -f shadow R U S T
        rustc -o $binary $1
        ./$binary;;
    "py")
        figlet -f shadow P y
        python3 $1;;
    "tex")
        figlet -f shadow L a T e X
        tectonic $1;;
    "java")
        figlet -f shadow J a v a
        java $1;;
    "kt")
        figlet -f shadow K o t l i n
        kotlinc $1 -include-runtime -d $binary.jar
        java -jar $binary.jar;;
esac
