#!/bin/bash

DpreCONFfile="$HOME/.config/sucklessutils/addons_dwm/.dmenu.conf"
[ -f $DpreCONFfile ] && DpreCONF=$(bash $DpreCONFfile)

# Dont forget the slash at the end
BGDIR="$HOME/files/pictures/backgrounds/"

BGSEL=$(ls $BGDIR | $DpreCONF -l 10)
feh --no-fehbg --bg-center $BGDIR$BGSEL
