#!/bin/bash

set -e 

DpreCONF=$(bash dwmcfg dmenucolor)

# Dont forget the slash at the end
BGDIR="$HOME/files/pictures/backgrounds/"

BGSEL=$(ls $BGDIR | $DpreCONF -l 10)
if [ -n $BGSEL ];
then
	feh --no-fehbg --bg-fill $BGDIR$BGSEL
fi
