#!/bin/bash

set -e

# Unfinished tasks path:
taskPATH="$HOME/files/.tasks"

# Finished tasks path:
ftaskPATH="$HOME/files/.ftasks"

function checkFILE {
    if [ ! -f $ftaskPATH ];
    then
        touch $ftaskPATH
    fi
    if [ ! -f $taskPATH ];
    then
        echo "[1] Create New Task"
        read MTselCHOICE
        touch $taskPATH
        if [[ $MTselCHOICE = "1" ]];
        then
            createTASK
        fi
    else
        initMENU
    fi;
}

function createTASK {
    # function to create tasks
    echo "Input Task:"
    read taskDATA
    echo "$taskDATA" >> $taskPATH;
}

#function listTASK {
    allNrLINE=$(cat -n $taskPATH | sed '$!d' | awk '{print($1)}')
    varNR=1
    while [[ $varNR -lt $allNrLINE ]];
    do
        echo "[$varNR] $(cat $taskPATH | awk "NR==$varNR" )"
        varNR=$(($varNR+1))
    done
    echo "Select Task"
    read itemSelNrLINE
    selListCHOICE=$(cat $taskPATH | awk "NR==$itemSelNrLINE" )
    echo -e "Selected Task: $selListCHOICE\n[1] Finish\n[2] Delete\nModify Task:"
    read modTASK
    case $modTASK in
        "");;
        "1")
            sed -i "$itemSelNrLINE" $taskPATH
            echo "${selListCHOICE} // Finished Date: $(date +'%d-%m-%y, %H:%M')" >> $ftaskPATH;;
        "2")
            sed -i "$itemSelNrLINE" $taskPATH;;
        *);;
    esac;
#}
# Port most code from wmenu
