#!/bin/bash

## Requires full_make script


# Init Variables

# Paths to some files
swpPATH="$HOME/files/.dwmswp"
xresPATH="$HOME/.config/X11/Xresources"

# check if it's day or night
_TIME=$(date +%H)
if [[ $_TIME < 8 || $_TIME > 18 ]];
then
	# Night
	ToD=1
else
	# Day
	ToD=0
fi

# If swpPATH exists already set the themeDWM
if [ -f $swpPATH ];
then
	themeDWM=$(cat $swpPATH | awk '{print($2)}')
fi


# DWM Colors

# Dont put any spaces between names
themeNAME=( "Day" "Night" "Gray_Nights" "Calm_Purple" "Bright_Purple" )
themeSEL="n/a"
GRAY1=( "#d8dee9" "#130308" "#111111" "#111111" "#130308" )
GRAY2=( "#d8dee9" "#130308" "#111111" "#111111" "#444444" )
GRAY3=( "#5d5d5d" "#5d5d5d" "#5d5d5d" "#5d5d5d" "#bbbbbb" )
GRAY4=( "#eceff4" "#130308" "#111111" "#111111" "#eeeeee" )
CYAN=(  "#5e81ac" "#d08770" "#536878" "#903749" "#864c99" )
FONT="monospace:size=11"

#             			  fg     bg     border
# unselected bar color	{ GRAY3, GRAY1, GRAY2 }
# selected bar color 	{ GRAY4, CYAN,  CYAN  }


function xrdbMOD {
	sed -i "s/dwm\.normbordercolor\:.*$/dwm\.normbordercolor\:${GRAY2[$1]}/g" $xresPATH
	sed -i "s/dwm\.normbgcolor\:.*$/dwm\.normbgcolor\:${GRAY1[$1]}/g" $xresPATH
	sed -i "s/dwm\.normfgcolor\:.*$/dwm\.normfgcolor\:${GRAY3[$1]}/g" $xresPATH
	sed -i "s/dwm\.selbordercolor\:.*$/dwm\.selbordercolor\:${CYAN[$1]}/g" $xresPATH
	sed -i "s/dwm\.selbgcolor\:.*$/dwm\.selbgcolor\:${CYAN[$1]}/g" $xresPATH
	sed -i "s/dwm\.selfgcolor\:.*$/dwm\.selfgcolor\:${GRAY4[$1]}/g" $xresPATH
	xrdb -merge $xresPATH;
}


# Stands for Theme DWM
function Tdwm {
	# Checks length of list in themeNAME
	if [ $1 -gt $((${#themeNAME[@]}-1)) ];
	then
		echo "Not enough themes"
	else
		xrdbMOD $1
	fi;
}

# Stands for Theme Dmenu
function Tdmenu {
    case $1 in
        "");;
        *[0-9]*)
            if [ $1 -gt $((${#themeNAME[@]}-1)) ];
            then
	        	echo "Not enough themes"
            else
		        #                          UnSel BG         Unsel FG         Sel BG          UnSel FG
		        echo dmenu -fn $FONT -nb ${GRAY1[$1]} -nf ${GRAY3[$1]} -sb ${CYAN[$1]} -sf ${GRAY4[$1]}
            fi;;
        "nb")
            # Set $1 to the current DWM theme
            set $themeDWM
		    echo dmenu -fn $FONT -nf ${GRAY3[$1]} -sb ${CYAN[$1]} -sf ${GRAY4[$1]};;
        "nf")
            set $themeDWM
		    echo dmenu -fn $FONT -nb ${GRAY1[$1]} -sb ${CYAN[$1]} -sf ${GRAY4[$1]};;
        "sb")
            set $themeDWM
		    echo dmenu -fn $FONT -nb ${GRAY1[$1]} -nf ${GRAY3[$1]} -sf ${GRAY4[$1]};;
        "sf")
            set $themeDWM
		    echo dmenu -fn $FONT -nb ${GRAY1[$1]} -nf ${GRAY3[$1]} -sb ${CYAN[$1]};;
    esac;
}

function colorPrint {
    case $1 in
        "")
            echo ${GRAY1[$swpCHECK]} ${GRAY2[$swpCHECK]} ${GRAY3[$swpCHECK]} ${GRAY4[$swpCHECK]} ${CYAN[$swpCHECK]};;
        1)
            echo ${GRAY1[$swpCHECK]};;
        2)
            echo ${GRAY2[$swpCHECK]};;
        3)
            echo ${GRAY3[$swpCHECK]};;
        4)
            echo ${GRAY4[$swpCHECK]};;
        5)
            echo ${CYAN[$swpCHECK]};;
    esac;
}

# check if its day or night then start the appropriate DWM theme
# Stands for Day 'n Night DWM
function DNdwm {
	if [ -f $swpPATH ];
	then
		themeDWM=$(cat $swpPATH | awk '{print($2)}')
		Tdwm $themeDWM
	else
		Tdwm $ToD
	fi;
}

# check if its day or night then start the appropriate Dmenu theme
# Stands for Day 'n Night Dmenu
function DNdmenu {
	if [ -f $swpPATH ];
	then
		themeDWM=$(cat $swpPATH | awk '{print($2)}')
		Tdmenu $themeDWM
	else
		Tdmenu $ToD
	fi;
}

# check if DWM is running and if it is then pkill it
function pkillDWM {
	if [ $(($(pgrep dwm | wc -l)-2)) == 0 ];
	then
		echo "dwm isn't running"
	else
		pkill dwm
	fi;
}

# function to input "theme 0/1/.."
function swpMOD {
	rm $swpPATH
	themeSEL=${themeNAME[$1]}
	echo "theme $1" >> $swpPATH;
}

function FthemeSEL {
	swpCHECK=$(cat $swpPATH | awk '{print($2)}')
    if [[ $1 != "echo" ]];
    then
        themeSEL=${themeNAME[$swpCHECK]}
        echo $themeSEL
    fi;
}

# Arguments for the script
case $1 in
	"")
		DNdwm;;
 	theme)
		swpMOD $2
		Tdwm $2
		pkillDWM;;
	compile)
		bash full_make dwm
		DNdwm
		pkillDWM;;
	# Deprecated since useless {
	rload|rset)
		DNdwm
		pkillDWM;;
	# }
	dmenucolor)
		DNdmenu;;
    tdmenu)
        Tdmenu $2;;
	pkill)
		pkillDWM;;
	swpPATH)
		echo $swpPATH;;
	swpMOD)
		swpMOD $2;;
	allthemes)
		echo "${themeNAME[@]}";;
	seltheme)
		FthemeSEL;;
	colors)
		FthemeSEL echo
        colorPrint $2;;
esac



# Use cases

# Compile and then starts DWM with last applied theme/ and if not specified starts the day/night theme appropriately
# dwmcfg compile

# Simple kill and reset/reload of the DWM config
# dwmcfg rload/rset

# Apply a theme set at the Color Lists based on the List index
# dwmcfg theme 0/1/..


# External Bash scripts arguments

# Call the Dmenu pre configured arguments based on the current theme
# dwmcfg dmenucolor

# Echo string of all the themes configured in dwmcfg
# dwmcfg allthemes

# Echo selected theme name
# dwmcfg seltheme

# Kill DWM if it's running, without killing the X server (Useful if it's used in bashscripts that don't want the X server to go down after DWM is killed)
# dwmcfg pkill

# Call the .dwmswp file path (Useful for bashscripts)
# dwmcfg swpPATH

# Specify in the .dwmswp file "0/1/.." to select a new theme
# dwmcfg swpMOD 0/1/2/3..
