#!/bin/bash

## Requires full_make script


# Init Variables

# Paths to some files
swpPATH="$HOME/.dwmswp"
xresPATH="$HOME/.config/X11/Xresources"

# check if it's day or night
_TIME=$(date +%H)
if [[ $_TIME < 8 || $_TIME > 18 ]];
then
	# Night
	ToD=1
else
	# Day
	ToD=0
fi


# DWM Colors

# Custom[2]: Dark Purple
# Custom[3]: Gray Nights
#Colors	Day[0]    Night[1]  Custom[2] Custom[3]
GRAY1=( "#d8dee9" "#130308" "#130308" "#111111" )
GRAY2=( "#eceff4" "#444444" "#ffffff" "#111111" ) 
GRAY3=( "#4c566a" "#bbbbbb" "#f2dcbb" "#5d5d5d" )
GRAY4=( "#eceff4" "#130308" "#130308" "#111111" )
CYAN=(  "#5e81ac" "#d08770" "#903749" "#536878" )

# Border color must be changed at dwm config.h
# 			  fg     bg     border
# unselected bar color	{ GRAY3, GRAY1, GRAY2 }
# selected bar color 	{ GRAY4, CYAN,  CYAN  }


function xrdbMOD {
	sed -i "s/dwm\.normbordercolor\:.*$/dwm\.normbordercolor\:${GRAY2[$1]}/g" $xresPATH
	sed -i "s/dwm\.normbgcolor\:.*$/dwm\.normbgcolor\:${GRAY1[$1]}/g" $xresPATH
	sed -i "s/dwm\.normfgcolor\:.*$/dwm\.normfgcolor\:${GRAY3[$1]}/g" $xresPATH
	sed -i "s/dwm\.selbordercolor\:.*$/dwm\.selbordercolor\:${CYAN[$1]}/g" $xresPATH
	sed -i "s/dwm\.selbgcolor\:.*$/dwm\.selbgcolor\:${CYAN[$1]}/g" $xresPATH
	sed -i "s/dwm\.selfgcolor\:.*$/dwm\.selfgcolor\:${GRAY4[$1]}/g" $xresPATH
	xrdb -merge $xresPATH
}


# Stands for Theme DWM
function Tdwm {
	# Checks length of list in GRAY1 because theyre most likely the same length
	if [ $1 -gt $((${#GRAY1[@]}-1)) ];
	then
		echo "Not enough themes"
	else
		xrdbMOD $1
	fi
}

# Stands for Theme Dmenu
function Tdmenu {
	if [ $1 -gt $((${#GRAY1[@]}-1)) ];
	then
		echo "Not enough themes"
	else
		#              UnSel BG         Unsel FG         Sel BG          UnSel FG
		echo dmenu -nb ${GRAY1[$1]} -nf ${GRAY3[$1]} -sb ${CYAN[$1]} -sf ${GRAY4[$1]};
	fi
}

# check if its day or night then start the appropriate DWM theme
# Stands for Day 'n Night DWM
function DNdwm {
	if [ -f $swpPATH ];
	then
		themeDWM=$(cat $swpPATH | awk '{print($2)}')
		Tdwm $themeDWM
	else
		Tdwm $ToD
	fi;
}

# check if its day or night then start the appropriate Dmenu theme
# Stands for Day 'n Night Dmenu
function DNdmenu {
	if [ -f $swpPATH ];
	then
		themeDWM=$(cat $swpPATH | awk '{print($2)}')
		Tdmenu $themeDWM
	else
		Tdmenu $ToD
	fi;
}

# check if DWM is running and if it is then pkill it
function pkillDWM {
	if [ $(($(pgrep dwm | wc -l)-2)) == 0 ];
	then
		echo "dwm isn't running" 
	else
		pkill dwm
	fi
}

# function to input "theme 0/1/.."
function swpMOD {
	rm $swpPATH
	echo "theme $1" >> $swpPATH;
}

# Arguments for the script
case $1 in
	"")
		DNdwm;;
 	theme)
		swpMOD $2
		Tdwm $2
		pkillDWM;;
	compile)
		bash full_make dwm
		DNdwm
		pkillDWM;;
	rload|rset)
		DNdwm
		pkillDWM;;
	dmenucolor)
		DNdmenu;;
	pkill)
		pkillDWM;;
	swpPATH)
		echo $swpPATH;;
	swpMOD)
		swpMOD $2;;
esac


# Use cases

# Compile and then starts DWM with last applied theme/ and if not specified starts the day/night theme appropriately
# dwmcfg compile

# Simple kill and reset/reload of the DWM config
# dwmcfg rload/rset

# Apply a theme set at the Color Lists based on the List index
# dwmcfg theme 0/1/..


# External Bash scripts arguments

# Call the Dmenu pre configured arguments based on the current theme
# dwmcfg dmenucolor

# Kill DWM if it's running, without killing the X server (Useful if it's used in bashscripts that don't want the X server to go down after DWM is killed)
# dwmcfg pkill

# Call the .dwmswp file path (Useful for bashscripts)
# dwmcfg swpPATH

# Specify in the .dwmswp file "0/1/.." to select a new theme
# dwmcfg swpMOD 0/1/2/3..
