#!/bin/bash

# Sucklessutils make install function
function makeInstall {
	# rm -f $HOME/.config/sucklessutils/$1/config.h
	cd $HOME/.config/sucklessutils/$1/
	sudo make install
	cd $HOME
}

if [[ $1 != "" ]];
then
    makeInstall $1
else
    # Manually add ones that arent here
	makeInstall dwm
	makeInstall slstatus
	makeInstall sxiv
	makeInstall st
fi
