#!/bin/bash

# Sucklessutils make install function
function makeInstall {
	rm -f $HOME/.config/sucklessutils/$1/config.h
	cd $HOME/.config/sucklessutils/$1/
	sudo make install
	cd $HOME
}

# Addons_dwm
cd $HOME/.config/sucklessutils/addons_dwm/
chmod +x ./*
sudo cp ./* /usr/local/bin/
cd $HOME

case $1 in
	"")
		makeInstall dwm
		makeInstall slstatus
		makeInstall sxiv
		makeInstall st;;
	dwm)
		makeInstall dwm;;
	slstatus)
		makeInstall slstatus;;
	sxiv)
		makeInstall sxiv;;
	st)
		makeInstall st;;
esac
