#!/bin/bash

xdotool key q
sleep 0.2s
xdotool key h
sleep 0.2s
xdotool key j
sleep 0.2s
xdotool key l
sleep 0.2s
xdotool key l
sleep 0.2s
xdotool key f
sleep 0.2s
xdotool key equal
sleep 0.2s
for ((i=0;i<=10;i++));
do
    xdotool key k
done
