#!/bin/bash

tmpPATH="/mnt/tmpfs/mpccur"
time_left=$(mpc | awk 'NR==2' | awk '{print($3)}')
mpdP=$(mpc status | grep playing)
#  check if mpd is playing  
if [[ $mpdP = "" ]];
then
    outputVAR=" "
else
    outputVAR=" "
fi
current=$(mpc current)
current=${current%.*}
current=( $(echo $current | sed -r 's#.*/##g') )
if [ ${#current[@]} -gt 7 ];
then
    outputVAR+="$(echo ${current[@]} | sed -r 's#.*-##g')"
else
    outputVAR+="${current[@]}"
fi

if [ -f $tmpPATH ];
then
    if [[ $1 = "time" ]];
    then
        rm $tmpPATH
        echo $outputVAR
    else
        touch $tmpPATH
        echo "$outputVAR ($time_left)"
    fi
else
    if [[ $1 = "time" ]];
    then
        touch $tmpPATH
        echo "$outputVAR ($time_left)"
    else
        echo $outputVAR
    fi
fi
