#!/bin/bash

set -e

DpreCONF=$(dwmcfg dmenucolor)

DOVAR=$(echo -e "kill dwm\npoweroff\nreboot\nhalt" | $DpreCONF -l 4 )
echo $DOVAR
if [[ $DOVAR == "kill dwm" ]]; then
	pkill xinit
else
	sudo $DOVAR
fi
