#!/bin/bash

# DMENU conf
DpreCONFfile="$HOME/.config/sucklessutils/addons_dwm/.dmenu.conf"
[ -f $DpreCONFfile ] && DpreCONF=$(bash $DpreCONFfile)

WINDOWNAME=$(cat $HOME/.config/sucklessutils/addons_dwm/.windowlist | dmenu -l 10)
sed -i "/^$WINDOWNAME$/d" ~/.config/sucklessutils/addons_dwm/.windowlist
xdotool search --name "$WINDOWNAME" windowmap
