#!/bin/bash

## Requires dwmcfg script

set -e

# DpreCONF String and all themes specified in dwmcfg
DpreCONF=$(bash dwmcfg dmenucolor)
listNAME=( $(bash dwmcfg allthemes) )

# Replace the spaces between names with a new line(\n)
themeSTR=$(echo ${listNAME[@]} | sed -r 's/ /\\n/g')

doVAR=$(echo -e $themeSTR | $DpreCONF -i -l 5 )

i=0
while [[ $i < ${#listNAME[@]} ]];
do
#   Testing purposes
#	echo ${listNAME[$i]}
	if [[ $doVAR == ${listNAME[$i]} ]];
	then
		bash dwmcfg theme $i
		break
	fi
	i=$(( $i + 1 ))
done
