#!/bin/bash

## Requires dwmcfg script

set -e

DpreCONF=$(bash dwmcfg dmenucolor)

themeList=( "Day" "Night" "Dark Purple" "Gray Nights" )

DOVAR=$(echo -e "${themeList[3]}\n${themeList[2]}\n${themeList[0]}\n${themeList[1]}" | $DpreCONF -l 5 )

case $DOVAR in
	"");;
	${themeList[0]})
		bash dwmcfg theme 0;;
	${themeList[1]})
		bash dwmcfg theme 1;;
	${themeList[2]})
		bash dwmcfg theme 2;;
	${themeList[3]})
		bash dwmcfg theme 3;;
esac
