#!/bin/bash

## Requires dwmcfg script

set -e

DpreCONF=$(bash dwmcfg dmenucolor)

DOVAR=$(echo -e "restart\ncompile\nday\nnight\ntheme1\ntheme2" | $DpreCONF -l 5 )

case $DOVAR in
	"");;
	day)
		bash dwmcfg theme 0;;
	night)
		bash dwmcfg theme 1;;
	theme1)
		bash dwmcfg theme 2;;
	theme2)
		bash dwmcfg theme 3;;
	restart)
		bash dwmcfg rload;;
	compile)
		bash dwmcfg compile;;
esac
