#!/bin/sh

# STARTING UP PROGRAMS

# MPD configure
mpd & # Start mpd
mpc pause &
touch /mnt/tmpfs/mpccur & # Show song progress in dwm bar

# Start transmission
transmission-daemon --download-dir "$HOME/files/downloads/" & # Start transmission

# Start Syncthing
/bin/syncthing serve --no-browser &>/dev/null &
