#!/bin/bash

tmpPATH="/var/tmp/vol"

if [ -f $tmpPATH ];
then
    currentVOL=$(cat $tmpPATH | grep "VOL" | awk '{print($2)}')
    prevNotifID=$(cat $tmpPATH | grep "ID" | awk '{print($2)}')
    muteVOL=$(cat $tmpPATH | grep "MUTE" | awk '{print($2)}')
    dunstify -C $prevNotifID
else
    muteVOL=0
    currentVOL=100
fi


function volMOD {
    amixer set Master $currentVOL%
    if [[ $muteVOL -eq 1 ]];
    then
        notifID=$(dunstify -i /dev/null " Volume: $currentVOL%" -p)
    else
        notifID=$(dunstify -i /dev/null " Volume: $currentVOL%" -p)
    fi
    rm $tmpPATH
    touch $tmpPATH
    echo -e "VOL $currentVOL\nID $notifID\nMUTE $muteVOL" >> $tmpPATH
}

case $1 in
    "")
        ;;
    set)
       amixer set Master unmute
       amixer set Master $2%
       muteVOL=0
       currentVOL=$(echo $2)
       rm $tmpPATH
       touch $tmpPATH
       echo -e "VOL $currentVOL\nID $notifID\nMUTE $muteVOL" >> $tmpPATH;;
    inc)
       currentVOL=$(($currentVOL+$2))
       if [ $currentVOL -ge 100 ];
       then
           currentVOL=100
       fi
       volMOD;;
    dec)
       currentVOL=$(($currentVOL-$2))
       if [ $currentVOL -le 0 ];
       then
           currentVOL=0
       fi
       volMOD;;
   toggle)
       if [[ $muteVOL -eq 1 ]];
       then
           muteVOL=0
           notifID=$(dunstify -i /dev/null " Unmuted" -p)
           amixer set Master unmute
       else
           muteVOL=1
           notifID=$(dunstify -i /dev/null " Muted" -p)
       amixer set Master mute
       fi
       rm $tmpPATH
       touch $tmpPATH
       echo -e "VOL $currentVOL\nID $notifID\nMUTE $muteVOL" >> $tmpPATH;;
   vol)
       echo $currentVOL;;
esac
