#!/usr/bin/python3.9
import bs4
import requests
from datetime import datetime

def extract_source(url):
     agent = {"User-Agent":"Mozilla/5.0"}
     source=requests.get(url, headers=agent).text
     return source

def extract_data(source, strc, tpe, attr):
     soup=bs4.BeautifulSoup(source, 'html.parser')
     names=soup.find_all(strc, attrs={tpe:attr})
     return names

def extract_text(soup):
    temps = []
    for i in range(len(soup)):
        temps.append(soup[i].text.split('°')[0])
    return temps

apprx_list = extract_text(extract_data(extract_source('https://www.accuweather.com/en/xk/prishtina/298740/weather-forecast/298740'), strc='div', tpe='class', attr='temp'))
hourly_list = extract_data(extract_source('https://www.accuweather.com/en/xk/prishtina/298740/hourly-weather-forecast/298740'), strc='div', tpe='class', attr='temp metric')

# Extract daily
daily_site=extract_source('https://www.accuweather.com/en/xk/prishtina/298740/daily-weather-forecast/298740')
daily_high = extract_data(daily_site, strc='span', tpe='class', attr='high')
daily_low = extract_data(daily_site, strc='span', tpe='class', attr='low')
daily_day = extract_data(daily_site, strc='span', tpe='class', attr='module-header dow date')
daily_date = extract_data(daily_site, strc='span', tpe='class', attr='module-header sub date')


try:
    print("Current:",apprx_list[0],
          "\nToday:",apprx_list[1],
          "\nTonight:",apprx_list[2],
          "\nTomorrow:",apprx_list[3])
except Exception:
    print("Current:",apprx_list[0],
          "\nTonight:",apprx_list[1],
          "\nTomorrow:",apprx_list[2])

current_hour=datetime.now().hour + 1

print("\nHourly",end="")
for i in range(len(hourly_list)):
    print(end="\n| ")
    if ( (current_hour + i) > 24 ):
        print(current_hour + i - 24, end="")
    else:
        print(current_hour + i, end="")
    print(" =",repr(hourly_list[i].text[0:-1])[7:-3], end=" | ")
print()

print("\nDaily")
for i in range(len(daily_high)):
    print("|", daily_day[i].text, "-", daily_date[i].text, "=",daily_high[i].text, "/", daily_low[i].text[1:], end=" | \n")
print()
