#!/bin/bash

## Requires dwmcfg script

set -e


### 3-# mark the variables that can be modified

# DpreCONF String and task path
# Modify if not using the dwmcfg script:
DpreCONF=$(bash dwmcfg dmenucolor)
DpreCONFsb=$(bash dwmcfg tdmenu sb)

# Unfinished tasks path:
taskPATH="$HOME/.tasks"

# Finished tasks path:
ftasksPATH="$HOME/.ftasks"

# Set createTASK function colors:
colors=( "#d08770" "#536878" "#903749" "#5e81ac" )

# Easy way to set the task 1/2/3/4/5/.. hours from now
premadeHOUR=( 1 2 3 4 5 6 12 )
# Do not change:
for hour in "${premadeHOUR[@]}";
do
    hourSTR+="$hour Hour(s) from now\n"
done

# Easy way to set the task 1/2/3/4/5/.. days from now:
premadeDAY=( 1 2 3 4 5 10 30 )
# Do not change:
for day in "${premadeDAY[@]}";
do
    daySTR+="$day Day(s) from now\n"
done

###

# The 2 below functions are for arithmetic purposes
function checkNremoveZERO {
    if [[ $1 -ge 10 ]];
    then
        echo $1
    else
        tmpVAR0=$(echo $1 | sed -r 's/0//g')
        echo $tmpVAR0
    fi
}

function checkNaddZERO {
    if [[ $1 -ge 10 ]];
    then
        echo $1
    else
        tmpVAR1+="0$1"
        echo $tmpVAR1
    fi
}

# todayDATE=$(checkNremoveZERO $(date +%D))
todayDAY=$(checkNremoveZERO $(date +%d))
todayMONTH=$(checkNremoveZERO $(date +%m))
todayYEAR=$(checkNremoveZERO $(date +%y))
todayHOUR=$(checkNremoveZERO $(date +%H))
todayMIN=$(checkNremoveZERO $(date +%M))
extraDAY=0

function checkFILE {
    if [ ! -f $taskPATH ];
    then
        MTselCHOICE=$(echo "Create New Task" | $DpreCONF -l 1 -p "0-tasks")
        touch $taskPATH
        if [[ $MTselCHOICE = "Create New Task" ]];
        then
            createTASK
        fi
    else
        initMENU
    fi;
}

function taskDATEf {
    taskDAY="false"
    globalDAY=0
    globalMONTH=0
    globalYEAR=0
    while [[ $taskDAY = "false" ]];
    do
        taskDAY=$(echo -e "$daySTR""Input date DD/MM/YY e.g. 4/5/14" | $DpreCONFsb -sb ${colors[3]} -l 10 -p "Task Date")
        for days in ${premadeDAY[@]};
        do
            if [[ $taskDAY = *"Day(s) from now"* ]];
            then
                if [[ $taskDAY = "$days Day(s) from now" ]];
                then
                    accurateDAY=$(($todayDAY+$days+$extraDAY))
                    daysPlusExtraDAY=$(checkNremoveZERO $accurateDAY)
                    if [[ $todayMONTH == 2 && $daysPlusExtraDAY -gt 28 ]];
                    then
                        globalDAY=$(($todayDAY+$days+$extraDAY-28))
                        globalMONTH=$(($todayMONTH+1))
                        globalYEAR=$todayYEAR
                        taskDAY="$globalDAY/$globalMONTH/$globalYEAR"
                        break
                    elif [[ $(($todayMONTH%2)) == 1 && $daysPlusExtraDAY -gt 30 ]];
                    then
                        globalDAY=$(($todayDAY+$days+$extraDAY-30))
                        globalMONTH=$(($todayMONTH+1))
                        globalYEAR=$todayYEAR
                        taskDAY="$globalDAY/$globalMONTH/$globalYEAR"
                        break
                    elif [[ $daysPlusExtraDAY -gt 31 ]];
                    then
                        globalDAY=$(($todayDAY+$days+$extraDAY-31))
                        globalMONTH=$(($todayMONTH+1))
                        globalYEAR=$todayYEAR
                        taskDAY="$globalDAY/$globalMONTH/$globalYEAR"
                        break
                    else
                        globalDAY=$(($todayDAY+$days+$extraDAY))
                        globalMONTH=$(($todayMONTH))
                        globalYEAR=$todayYEAR
                        taskDAY="$globalDAY/$globalMONTH/$globalYEAR"
                        break
                    fi
                fi
            else
                dayVAR=$(echo $taskDAY   | sed -r 's|/.*$||g')
                monthVAR=$(echo "$taskDAY" | awk -F'/' '{print $2}' )
                yearVAR=$(echo $taskDAY  | sed -r 's|.*/||g')
                dayVAR=$(checkNremoveZERO $dayVAR)
                monthVAR=$(checkNremoveZERO $monthVAR)
                yearVAR=$(checkNremoveZERO $yearVAR)
                break
            fi
        done

        # Check if dayVAR, monthVAR and yearVAR are ALL declared
        if [[ -n ${dayVAR+x} && -n ${dayVAR+x} && -n ${dayVAR+x} ]];
        then
            if [[ $yearVAR -lt $todayYEAR || $yearVAR -gt 99 ]];
            then
                taskDAY="false"
            elif [[ $yearVAR == $todayYEAR ]];
            then
                isThisYEAR=1
                if [[ $monthVAR -lt $todayMONTH || $monthVAR -gt 12 ]];
                then
                    taskDAY="false"
                elif [[ $monthVAR == $todayMONTH ]];
                then
                    isThisMONTH=1
                    if [[ $dayVAR -lt $todayDAY ]];
                    then
                        taskDAY="false"
                    elif [[ ( $monthVAR == 2 && $dayVAR -gt 28 ) || ( $(($monthVAR%2)) == 1 && $dayVAR -gt 30 ) || $dayVAR -gt 31 ]];
                    then
                        taskDAY="false"
                    elif [[ $dayVAR == $todayDAY ]];
                    then
                        isThisDAY=1
                        if [[ $hourVAR -lt $todayHOUR ]];
                        then
                            taskHOURf
                            taskDAY="false"
                        elif [[ $hourVAR == $todayHOUR ]];
                        then
                            isThisHOUR=1
                            if [[ $isThisHOUR == 1 && $minVAR -lt $todayMIN ]];
                            then
                                taskHOURf
                                taskDAY="false"
                            fi
                        fi
                    fi
                fi
            fi
        fi
    done;
}

function taskHOURf {
    globalHOUR=0
    globalMIN=0
    taskHOUR="false"
    while [[ $taskHOUR = "false" ]];
    do
        taskHOUR=$(echo -e "$hourSTR""Input hour HH:MM e.g. 19:20" | $DpreCONFsb -sb ${colors[2]} -l 10 -p "Task Hour")
        for hours in ${premadeHOUR[@]};
        do
            echo "hours" $hours
            if [[ $taskHOUR = *"Hour(s) from now"* ]];
            then
                if [[ $taskHOUR = "$hours Hour(s) from now" ]];
                then
                    echo $(($todayHOUR+$hours))
                    if [[ $(($todayHOUR+$hours)) -gt 23 ]];
                    then
                        echo "greater than 23:" $taskHOUR
                        extraDAY=1
                        globalHOUR=$(($todayHOUR+$hours-24))
                        globalMIN=$todayMIN
                        taskHOUR="$globalHOUR:$globalMIN"
                        break
                    else
                        echo "less than 23:" "h" $hours "taskHOUR" $taskHOUR
                        globalHOUR=$(($todayHOUR+$hours))
                        globalMIN=$todayMIN
                        taskHOUR="$globalHOUR:$globalMIN"
                        break
                    fi
                fi
            else
                hourVAR=$(echo $taskHOUR | sed -r 's/:.*$//g')
                minVAR=$(echo $taskHOUR | sed -r 's/.*://g')
            fi
        done
        if [[ -n ${hourVAR+x} && -n ${minVAR+x} ]];
        then
            if [[ $hourVAR -gt 23 || $minVAR -gt 59 ]];
            then
                taskHOUR="false"
            else
                globalHOUR=$hourVAR
                globalMIN=$minVAR
                taskHOUR="$hourVAR:$minVAR"
            fi
        fi
    done;
}

function createTASK {
    echo "createTASK1"
    # function to create tasks
    taskTITLE=$(cat /dev/null | $DpreCONFsb -sb ${colors[0]} -p "Task Title" )
    echo "createTASK2"
    taskDESCRIPTION=$(cat /dev/null | $DpreCONFsb -sb ${colors[1]} -p "Task Description" )
    echo "createTASK3"
    taskHOURf
    echo "createTASK4"
    taskDATEf
    echo "createTASK5"
    echo "$taskTITLE|$taskDESCRIPTION|$taskHOUR|$taskDAY" >> $taskPATH
    echo "createTASK6"
}

function initMENU {
    # Menu when initialized
    selCHOICE=$(echo -e "Create New Task\nList Tasks" | $DpreCONF -l 2 -p "Start Menu")
    case $selCHOICE in
        "");;
        "Create New Task")
            createTASK;;
        "List Tasks")
            listTASK;;
    esac;
}

case $1 in
    "")
        checkFILE;;
    create)
        createTASK;;
    menu)
        initMENU;;
esac

# Use cases
# If 0 tasks, prompt to create a new task

# TO-DO
# add the list, finish, delete and edit functions
