#!/bin/bash

## Requires dwmcfg script(for dmenu themeing)

set -e

### 3-# mark the variables that can be modified

# DpreCONF String and task path
# Modify if not using the dwmcfg script:
DpreCONF=$(bash dwmcfg dmenucolor)
DpreCONFsb=$(bash dwmcfg tdmenu sb)

# Unfinished tasks path:
taskPATH="$HOME/files/.tasks"

# Finished tasks path:
ftaskPATH="$HOME/files/.ftasks"

# Set createTASK function colors:
color="#903749"

###

function checkFILE {
    if [ ! -f $ftaskPATH ];
    then
        touch $ftaskPATH
    fi
    if [ ! -f $taskPATH ];
    then
        MTselCHOICE=$(echo "Create New Task" | $DpreCONF -l 1 -p "0-tasks")
        touch $taskPATH
        if [[ $MTselCHOICE = "Create New Task" ]];
        then
            createTASK
        fi
    else
        initMENU
    fi;
}

function createTASK {
    # function to create tasks
    taskDATA=$(cat /dev/null | $DpreCONFsb -sb $color -p "Task-" )
    echo "$taskDATA" >> $taskPATH;
}


function listTASK {
    selListCHOICE=$(cat $taskPATH | $DpreCONF -l 10 -p "Select Task" )
    itemSelNrLINE=$(cat -n $taskPATH | grep "$selListCHOICE" | awk '{print($1)}')
    itemSelNrLINE=$(echo $itemSelNrLINE | sed -r 's/ /\d;/g' )
    itemSelNrLINE+="d"
    modTASK=$(echo -e "Selected Task: $selListCHOICE\nFinish\nDelete" | $DpreCONF -l 3 -p "Modify Task" )
    case $modTASK in
        "");;
        "Finish")
            sed -i "$itemSelNrLINE" $taskPATH
            echo "${selListCHOICE} // Finished Date: $(date +'%d-%m-%y, %H:%M')" >> $ftaskPATH;;
        "Delete")
            sed -i "$itemSelNrLINE" $taskPATH;;
        *);;
    esac;
}

function initMENU {
    # Menu when initialized
    selMenuCHOICE=$(echo -e "Create New Task\nList Tasks" | $DpreCONF -l 2 -p "Start Menu")
    case $selMenuCHOICE in
        "");;
        "Create New Task")
            createTASK;;
        "List Tasks")
            listTASK;;
    esac;
}

case $1 in
    "")
        checkFILE;;
    create)
        createTASK;;
    menu)
        initMENU;;
esac
