#!/bin/bash

selDIR=( $(ls | grep .zip) )
zipNR=${#selDIR[@]}
counter=0
# echo "Number of Zip files: "$zipNR
echo -e "\n---The found Zip files: "${selDIR[@]}
for item in ${selDIR[@]};
do
    if [[ ${counter} -lt $(($zipNR-2)) ]];
    then
        echo -e "\n>>> DELETE SUCCEDED"
        mkDIR=$(echo $item | sed -r 's/\.zip//g')
        mkdir -p $mkDIR
        unzip -n $item -d $mkDIR
        rm $item
    else
        echo -e "\n>>> DELETE DENIED"
        mkDIR=$(echo $item | sed -r 's/\.zip//g')
        mkdir -p $mkDIR
        unzip -n $item -d $mkDIR
    fi
    counter+=1
done
