#!/bin/sh

# Short aliases
alias \
	vim=nvim \
	vi=nvim \
	v=nvim \
	x=startx \
    ranger="ranger --cachedir=/dev/null" \
    rg=ranger \
    sxiv="sxiv -pqa" \
    s=sxiv \
    n=ncmpcpp \
    d=disown \
    z=zathura \
    h=htop
#   emacs=emacsclient \
#   e=emacs \

# PKG Manager
alias \
	xbi="sudo xbps-install -S" \
	xbu="sudo xbps-install -Su" \
	xbr="sudo xbps-remove" \
	xbq="xbps-query" \
	xbqr="xbps-query -Rs" \
	xbql="xbps-query -l"

# Navigation rel
alias \
	ls="ls --color=auto" \
	ll="ls -lGh" \
	lm="ls -lSh" \
	la="ll -a" \
	cl=clear

# .config
alias \
	cddwm="cd $HOME/.config/sucklessutils/dwm/" \
	cdst="cd $HOME/.config/sucklessutils/st/" \
	cdad="cd $HOME/.config/sucklessutils/addons_dwm/" \
	cdsl="cd $HOME/.config/sucklessutils/" \
	cdz="cd $HOME/.config/zsh/" \
	cdx="cd $HOME/.config/X11/"

# files
alias \
	cdf="cd $HOME/files/" \
    cdsc="cd $HOME/files/sync/" \
	cdp="cd $HOME/files/projects/" \
	cdg="cd $HOME/files/github/" \
	cdv="cd $HOME/files/videos/" \
	cdm="cd $HOME/files/music/" \
	cds="cd $HOME/files/pictures/screenshots/" \
	cdpp="cd $HOME/files/pictures/" \
	cdgv="cd $HOME/files/github/voidrice" \
	cdd="cd $HOME/files/downloads/" \
	cdh="cd $HOME && clear"

# GitHub
alias \
    ga="git add" \
    gs="git status" \
    gc="git commit -m" \
    gp="git push -u origin main"

# Manga-py
#alias \
#    mgi="manga-py -d ~/files/manga -r -R" \
#    mgl="manga-py -d ~/files/manga -r -R -c 1"

# Youtube rel
alias \
    yt="ytfzf -t" \
    yts="ytfzf -t --subs=3" \
    yta="bash ythelp a" \
    ytaa="bash ythelp a urlz" \
    ytv="bash ythelp v" \
    ytvv="bash ythelp v urlz" \
    mpv="mpv -ytdl-format='bestvideo[ext=mp4][width<=1920][height<=1080]+bestaudio[ext=m4a]'"

# Streamlink
alias \
    sl="streamlink --default-stream best --twitch-disable-ads --player mpv"

# Mpc
alias \
    mn="mpc next" \
    mp="mpc prev" \
    vinc="bash vol inc 3" \
    vdec="bash vol dec 3" \
    vtog="bash vol toggle"

# transmission
alias \
    magnet="transmission-remote -a" \
    torrent="transmission-remote -n 'transmission:transmission' -a"

# Random
alias \
    grep="grep --colour=auto" \
    fetch=neofetch \
	fetchb="neofetch --config $HOME/.config/neofetch/config_big.conf" \
    tclock="tty-clock -Dc -C 4" \
    br="bash ./renew.dir" \
	am="alsamixer"
