#!/bin/bash

# Short aliases
alias \
	vim=nvim \
	v=nvim \
	e=nvim \
	x=startx \
    z=zathura

# PKG Manager
alias \
	xbi="sudo xbps-install -S" \
	xbr="sudo xbps-remove" \
	xbq="xbps-query" \
	xbqr="xbps-query -Rs" \
	xbql="xbps-query -l"

# CDs
alias \
	cddwm="cd $HOME/.config/sucklessutils/dwm/" \
	cdst="cd $HOME/.config/sucklessutils/st/" \
	cdad="cd $HOME/.config/sucklessutils/addons_dwm/" \
	cdsl="cd $HOME/.config/sucklessutils/" \
	cdz="cd $HOME/.config/zsh/" \
	cdx="cd $HOME/.config/X11/" \
	cdg="cd $HOME/files/github/" \
	cdv="cd $HOME/files/github/voidrice" \
	cdf="cd $HOME/files/" \
	cdh="cd $HOME && clear"

# GitHub
alias \
    ga="git add" \
    gs="git status" \
    gc="git commit -m" \
    gp="git push -u origin main"

# Random
alias \
    yt="ytfzf -t" \
	ls="ls --color=auto" \
	ll="ls -lGh" \
	la="ll -a" \
	cl=clear \
    br="bash ./renew.dir" \
    fetch=neofetch \
	fetchb="neofetch --config $HOME/.config/neofetch/config_big.conf" \
    tclock="tty-clock -Dc -C 6" \
	am="alsamixer"
