#!/bin/bash

# Short aliases
alias \
	vim=nvim \
	v=nvim \
	e=nvim \
	x=startx

# PKG Manager
alias \
	xbi="sudo xbps-install -S" \
	xbr="sudo xbps-remove" \
	xbq="xbps-query" \
	xbqr="xbps-query -Rs" \
	xbql="xbps-query -l"

# CDs
alias \
	cddwm="cd $HOME/.config/sucklessutils/dwm/" \
	cdad="cd $HOME/.config/sucklessutils/addons_dwm/" \
	cdsl="cd $HOME/.config/sucklessutils/" \
	cdz="cd $HOME/.config/zsh/" \
	cdx="cd $HOME/.config/X11/" \
	cdg="cd $HOME/files/github/" \
	cdf="cd $HOME/files/" \
	cdh="cd $HOME"

# Random
alias \
	ls="ls --color=auto" \
	ll="ls -lGh" \
	lla="ll -a" \
	cl=clear \
	neofetchb="neofetch --config $HOME/.config/neofetch/config_big.conf" \
	am="alsamixer"
