#!/bin/bash
#
# ~/.xinitrc
#

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

userresources=$HOME/.config/X11/Xresources
usermodmap=$HOME/.config/X11/Xmodmap

swpPATH=$(dwmcfg swpPATH)
swpCHECK=$(($(cat $swpPATH | grep "x" | wc -l)-2))

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi
 
xrandr -s 1600x900 &

libinput-gestures-setup start &
xbanish &
xset r rate 280 40 &

## Start the bgchange script with an argument (e.g. 5s, 5m,...)
# bash $HOME/.config/sucklessutils/addons_dwm/.bgchange 15m &
## Set wallpaper Xorg starts with, --no-fehbg doesnt create a ~/.fehbg file
feh --no-fehbg --bg-center $HOME/files/pictures/backgrounds/background_11.jpg &

# if [[ $time -gt 16 && $time -lt 12 ]];
# then

exec slstatus &
# exec dwm
rm $swpPATH &
exec bash dwmcfg &
while [ $swpCHECK != 0 ];
do
	swpCHECK=$(($(cat $swpPATH | grep "x" | wc -l)-2))
	sleep 1s
done
rm $swpPATH &
pkill xinit
