#!/bin/sh
#
# ~/.xinitrc
#

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

userresources=$HOME/.config/X11/Xresources
usermodmap=$HOME/.config/X11/Xmodmap

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi
 
xrandr -s 1600x900 &
urxvtd -q &

libinput-gestures-setup start &
xbanish &
xset r rate 280 40 &

## Start the bgchange script with an argument (e.g. 5s, 5m,...)
# bash $HOME/.config/sucklessutils/addons_dwm/.bgchange 15m &
## Set wallpaper Xorg starts with, --no-fehbg doesnt create a ~/.fehbg file
feh --no-fehbg --bg-center $HOME/files/pictures/backgrounds/background_11.jpg &
exec slstatus &
exec dwm
